#let meta = (
  text_font: ("Tinos", "TeX Gyre Termes"),
  cjk_font: ("AR PL SungtiL GB", "Droid Sans Fallback"),
  sans_font: ("Arimo", "Nimbus Sans"),
  mono_font: ("Cousine", "Nimbus Mono PS"),
  title_font: ("AR PL KaitiM GB", "AR PL KaitiM Big5"),
  university_name: "华中师范大学",
  thesis_label: "学位论文",
  title: "华中师范大学学位论文 Typst 模板",
  title_en: "CCNU Thesis Typst Template",
  author: "你的姓名",
  supervisor: "教师姓名 职称",
  department: "数学与统计学学院",
  major: "应用统计",
  degree: "本科",
  date: datetime.today().display("[year]-[month]-[day]"),
  keywords: ("关键词1", "关键词2", "关键词3"),
)
