#let meta = (
  text_font: ("Times New Roman", "Tinos", "TeX Gyre Termes"),
  cjk_font: ("SimSun", "Songti SC", "Source Han Serif SC", "Noto Serif CJK SC", "FandolSong"),
  sans_font: ("Arial", "Arimo", "Nimbus Sans"),
  mono_font: ("Courier New", "Cousine", "Nimbus Mono PS"),
  cover_title_font: ("STXinwei", "STKaiti", "KaiTi", "FandolHei"),
  university_name: "华中师范大学",
  thesis_label: "学位论文",
  title: "华中师范大学学位论文 Typst 模板",
  title_en: "CCNU Thesis Typst Template",
  author: "你的姓名",
  supervisor: "教师姓名 职称",
  department: "数学与统计学学院",
  major: "应用统计",
  degree: "本科",
  date: datetime.today().display("[year]-[month]-[day]"),
  keywords: ("关键词1", "关键词2", "关键词3"),
)
